version: '3.8' 

services:
  client:
    image: client
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: client
  server:
    image: server
    build:
      context: ./server/
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: server
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./server/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./server/mongo_data:/data/db
  nginx:
      image: nginx:1.20.1
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 8080:80
      container_name: reverse-proxy
      depends_on:
        - client
        - server